[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.processing]
  skip_processing = false
  
[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"