-- Add more recycling companies across South Africa
INSERT INTO recyclers (
  name, description, address, city, province, 
  phone, email, website, materials, verified,
  latitude, longitude, service_offerings, container_types,
  minimum_weight, operating_hours
) VALUES
  -- Add more SA Metal Group locations
  (
    'SA Metal Group - East London',
    'Eastern Cape metal recycling operations',
    '15 Settlers Way, Gately',
    'East London',
    'Eastern Cape',
    '043 745 1234',
    'el@sametal.co.za',
    'www.sametal.co.za',
    ARRAY['Ferrous Metals', 'Non-Ferrous Metals', 'E-Waste', 'Batteries'],
    true,
    -33.024456,
    27.899168,
    ARRAY['Collection', 'Drop-off', 'Container Rental'],
    ARRAY['Bags', '240L Bins', '6m³ Skips'],
    100.0,
    'Mon-Fri: 07:00-17:00, Sat: 07:00-12:00'
  ),
  (
    'SA Metal Group - Kimberley',
    'Northern Cape recycling facility',
    '45 Cecil Sussman Road, Kimberley',
    'Kimberley',
    'Northern Cape',
    '053 832 5678',
    'kim@sametal.co.za',
    'www.sametal.co.za',
    ARRAY['Ferrous Metals', 'Non-Ferrous Metals', 'E-Waste', 'Batteries'],
    true,
    -28.732320,
    24.762793,
    ARRAY['Collection', 'Drop-off', 'Container Rental'],
    ARRAY['Bags', '240L Bins', '6m³ Skips'],
    100.0,
    'Mon-Fri: 07:00-17:00, Sat: 07:00-12:00'
  ),
  
  -- Add more Reclam locations
  (
    'Reclam - Port Elizabeth',
    'Eastern Cape recycling operations',
    '25 Grahamstown Road, Deal Party',
    'Port Elizabeth',
    'Eastern Cape',
    '041 486 1234',
    'pe@reclam.co.za',
    'www.reclam.co.za',
    ARRAY['Paper', 'Plastic', 'Ferrous Metals', 'Non-Ferrous Metals'],
    true,
    -33.947977,
    25.591291,
    ARRAY['Collection', 'Drop-off', 'Container Rental'],
    ARRAY['Bags', '240L Bins', '6m³ Skips'],
    50.0,
    'Mon-Fri: 08:00-16:30'
  ),
  (
    'Reclam - Bloemfontein',
    'Free State recycling center',
    '17 Van Der Lingen Street, Hamilton',
    'Bloemfontein',
    'Free State',
    '051 447 8901',
    'bloem@reclam.co.za',
    'www.reclam.co.za',
    ARRAY['Paper', 'Plastic', 'Ferrous Metals', 'Non-Ferrous Metals'],
    true,
    -29.120275,
    26.214607,
    ARRAY['Collection', 'Drop-off', 'Container Rental'],
    ARRAY['Bags', '240L Bins', '6m³ Skips'],
    50.0,
    'Mon-Fri: 08:00-16:30'
  ),

  -- Add more Mpact Recycling locations
  (
    'Mpact Recycling - Durban',
    'KwaZulu-Natal recycling facility',
    '41 Circle Road, Maydon Wharf',
    'Durban',
    'KwaZulu-Natal',
    '031 274 6600',
    'durban@mpact.co.za',
    'www.mpactrecycling.co.za',
    ARRAY['Paper', 'Plastic', 'Cardboard'],
    true,
    -29.859680,
    31.021840,
    ARRAY['Collection', 'Drop-off', 'Container Rental'],
    ARRAY['Bags', '240L Bins'],
    100.0,
    'Mon-Fri: 08:00-16:30'
  ),
  (
    'Mpact Recycling - Port Elizabeth',
    'Eastern Cape recycling operations',
    '45 Villiers Road, Walmer',
    'Port Elizabeth',
    'Eastern Cape',
    '041 583 2147',
    'pe@mpact.co.za',
    'www.mpactrecycling.co.za',
    ARRAY['Paper', 'Plastic', 'Cardboard'],
    true,
    -33.980991,
    25.591290,
    ARRAY['Collection', 'Drop-off', 'Container Rental'],
    ARRAY['Bags', '240L Bins'],
    100.0,
    'Mon-Fri: 08:00-16:30'
  ),

  -- Add more Glass Recycling Company locations
  (
    'The Glass Recycling Company - Durban',
    'KwaZulu-Natal glass recycling facility',
    '35 Grimsby Road, Mobeni',
    'Durban',
    'KwaZulu-Natal',
    '031 461 7567',
    'durban@tgrc.co.za',
    'www.theglassrecyclingcompany.co.za',
    ARRAY['Glass'],
    true,
    -29.921900,
    31.001926,
    ARRAY['Collection', 'Drop-off'],
    ARRAY['Glass Banks', 'Bulk Containers'],
    500.0,
    'Mon-Fri: 08:00-16:30'
  ),
  (
    'The Glass Recycling Company - Pretoria',
    'Pretoria glass recycling operations',
    '56 Axle Drive, Silverton',
    'Pretoria',
    'Gauteng',
    '012 804 6810',
    'pretoria@tgrc.co.za',
    'www.theglassrecyclingcompany.co.za',
    ARRAY['Glass'],
    true,
    -25.735365,
    28.275198,
    ARRAY['Collection', 'Drop-off'],
    ARRAY['Glass Banks', 'Bulk Containers'],
    500.0,
    'Mon-Fri: 08:00-16:30'
  ),

  -- Add more Collect-a-Can locations
  (
    'Collect-a-Can - Durban',
    'KwaZulu-Natal can recycling facility',
    '27 Manchester Road, New Germany',
    'Durban',
    'KwaZulu-Natal',
    '031 705 4125',
    'durban@collectacan.co.za',
    'www.collectacan.co.za',
    ARRAY['Metal Cans', 'Aluminum Cans', 'Tin Cans'],
    true,
    -29.921900,
    31.001926,
    ARRAY['Collection', 'Drop-off', 'School Programs'],
    ARRAY['Bags', 'Can Cages'],
    50.0,
    'Mon-Fri: 08:00-16:30'
  ),
  (
    'Collect-a-Can - Pretoria',
    'Pretoria can recycling operations',
    '89 Derdepoort Road, Silverton',
    'Pretoria',
    'Gauteng',
    '012 804 7890',
    'pretoria@collectacan.co.za',
    'www.collectacan.co.za',
    ARRAY['Metal Cans', 'Aluminum Cans', 'Tin Cans'],
    true,
    -25.735365,
    28.275198,
    ARRAY['Collection', 'Drop-off', 'School Programs'],
    ARRAY['Bags', 'Can Cages'],
    50.0,
    'Mon-Fri: 08:00-16:30'
  ),

  -- Add more specialized recycling companies
  (
    'E-Waste Technologies',
    'Electronic waste recycling specialists',
    '78 Industrial Avenue, Strydom Park',
    'Johannesburg',
    'Gauteng',
    '011 789 4567',
    'info@ewaste-tech.co.za',
    'www.ewaste-tech.co.za',
    ARRAY['E-Waste', 'Batteries', 'Electronic Components'],
    true,
    -26.208790,
    28.984789,
    ARRAY['Collection', 'Drop-off', 'Data Destruction'],
    ARRAY['Secure Containers', 'Pallets'],
    100.0,
    'Mon-Fri: 08:00-17:00'
  ),
  (
    'Green Planet Recycling',
    'Comprehensive recycling solutions',
    '45 Edison Way, Montague Gardens',
    'Cape Town',
    'Western Cape',
    '021 551 7890',
    'info@greenplanet.co.za',
    'www.greenplanet.co.za',
    ARRAY['Paper', 'Plastic', 'Glass', 'Metal Cans', 'E-Waste'],
    true,
    -33.931139,
    18.539041,
    ARRAY['Collection', 'Drop-off', 'Container Rental'],
    ARRAY['Bags', '240L Bins', '6m³ Skips'],
    50.0,
    'Mon-Fri: 07:30-16:30, Sat: 08:00-13:00'
  ),
  (
    'Industrial Waste Solutions',
    'Industrial waste management specialists',
    '112 North Coast Road, Briardene',
    'Durban',
    'KwaZulu-Natal',
    '031 563 1234',
    'info@industrialwaste.co.za',
    'www.industrialwaste.co.za',
    ARRAY['Industrial Waste', 'Chemical Waste', 'Metal Scrap'],
    true,
    -29.921900,
    31.001926,
    ARRAY['Collection', 'Waste Management', 'Consulting'],
    ARRAY['Specialized Containers', 'Bulk Containers'],
    500.0,
    'Mon-Fri: 07:00-17:00'
  ),
  (
    'Battery Recycling Solutions',
    'Specialized battery recycling facility',
    '34 Forge Road, Benoni',
    'Johannesburg',
    'Gauteng',
    '011 845 6789',
    'info@batteryrecycling.co.za',
    'www.batteryrecycling.co.za',
    ARRAY['Batteries', 'Electronic Waste'],
    true,
    -26.208790,
    28.984789,
    ARRAY['Collection', 'Drop-off', 'Industrial Services'],
    ARRAY['Specialized Containers'],
    200.0,
    'Mon-Fri: 08:00-16:30'
  );

-- Add indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_recyclers_province ON recyclers(province);
CREATE INDEX IF NOT EXISTS idx_recyclers_city ON recyclers(city);
CREATE INDEX IF NOT EXISTS idx_recyclers_materials ON recyclers USING GIN(materials);
CREATE INDEX IF NOT EXISTS idx_recyclers_verified ON recyclers(verified);