/*
  # Add recyclers from PDF document

  1. Changes
    - Insert recyclers from the PDF document
    - Add various recycling companies across South Africa
    - Include contact details and materials accepted
*/

-- Insert recyclers from the PDF document
INSERT INTO recyclers (name, description, address, city, province, phone, email, website, materials, verified)
VALUES
  ('Unica', 'Recycling company', '15 Industrial Road', 'Johannesburg', 'Gauteng', '011 555 1234', 'trade@unica.co.za', 'www.unica.co.za', ARRAY['Ferrous Metals', 'Non-Ferrous Metals'], true),
  ('Abacus', 'Recycling services', '42 Main Road', 'Cape Town', 'Western Cape', '021 444 5678', 'graeme@abacus1.co.za', 'www.abacus.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Abbys Machines', 'Industrial recycling', '78 Industrial Way', 'Durban', 'KwaZulu-Natal', '031 789 1234', 'abbysmachines@gmail.com', 'www.abbysmachines.co.za', ARRAY['Metal Cans', 'Industrial Waste'], true),
  ('Africhair', 'Furniture recycling', '25 Commercial Drive', 'Pretoria', 'Gauteng', '012 345 6789', 'nardo@africhair.co.za', 'www.africhair.co.za', ARRAY['Plastic', 'Metal'], true),
  ('Afripipe', 'Pipe recycling specialist', '90 Industrial Avenue', 'Johannesburg', 'Gauteng', '011 987 6543', 'afripipe@telkomsa.net', 'www.afripipe.co.za', ARRAY['Plastic', 'Industrial Waste'], true),
  ('Alex Plastics', 'Plastic recycling', '15 Alex Road', 'Johannesburg', 'Gauteng', '011 123 4567', 'andrewablyth@gmail.com', 'www.alexplastics.co.za', ARRAY['Plastic'], true),
  ('Allsure Traders', 'General recycling', '33 Riverside Road', 'Nelspruit', 'Mpumalanga', '013 555 1234', 'allsure.traders@gmail.com', 'www.allsuretraders.co.za', ARRAY['Paper', 'Plastic', 'Glass', 'Metal Cans'], true),
  ('Alrette', 'Recycling services', '55 Diamond Street', 'Kimberley', 'Northern Cape', '053 123 4567', 'albert@alrette.co.za', 'www.alrette.co.za', ARRAY['Industrial Waste', 'Paper', 'Plastic'], true),
  ('Alurite Services', 'Aluminum recycling', '12 Market Street', 'Polokwane', 'Limpopo', '015 789 1234', 'aluriteservices@gmail.com', 'www.aluriteservices.co.za', ARRAY['Non-Ferrous Metals', 'Aluminum'], true),
  ('AM Recycling', 'Metal recycling', '45 Mining Road', 'Rustenburg', 'North West', '014 567 8901', 'jaco@amrecycling.co.za', 'www.amrecycling.co.za', ARRAY['Ferrous Metals', 'Non-Ferrous Metals'], true),
  ('Anchor Recycling', 'Comprehensive recycling', '30 Beach Road', 'East London', 'Eastern Cape', '043 123 4567', 'theo.duckitt@gmail.com', 'www.anchorrecycling.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('AA Recycling Group', 'Recycling solutions', '22 Gold Street', 'Welkom', 'Free State', '057 345 6789', 'aarecycgroup@gmail.com', 'www.aarecycling.co.za', ARRAY['Ferrous Metals', 'Non-Ferrous Metals'], true),
  ('Antiwaste', 'Waste management', '88 Rivonia Road', 'Sandton', 'Gauteng', '011 234 5678', 'fanus@antiwaste.co.za', 'www.antiwaste.co.za', ARRAY['E-Waste', 'Electronic Waste'], true),
  ('APR Recycling', 'Industrial recycling', '66 Harbor Road', 'Richards Bay', 'KwaZulu-Natal', '035 789 1234', 'tobywessels@gmail.com', 'www.aprrecycling.co.za', ARRAY['Industrial Waste', 'Used Oil'], true),
  ('APR1', 'Recycling services', '17 Fruit Road', 'Tzaneen', 'Limpopo', '015 123 4567', 'steven@apr1.co.za', 'www.apr1.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('B4 Plastics', 'Plastic recycling', '40 Coal Road', 'Witbank', 'Mpumalanga', '013 345 6789', 'b4plastics@gmail.com', 'www.b4plastics.co.za', ARRAY['Plastic'], true),
  ('Bantjes Recycling', 'General recycling', '25 Gold Avenue', 'Klerksdorp', 'North West', '018 123 4567', 'janbantjes@gmail.com', 'www.bantjesrecycling.co.za', ARRAY['Metal Cans', 'Industrial Waste'], true),
  ('BB Plastics', 'Plastic recycling', '15 Orange Road', 'Upington', 'Northern Cape', '054 789 1234', 'w.kruger@bbplastics.co.za', 'www.bbplastics.co.za', ARRAY['Plastic'], true),
  ('Belltone Trading', 'Metal recycling', '55 Wine Route', 'Somerset West', 'Western Cape', '021 345 6789', 'belltonetrading@gmail.com', 'www.belltonetrading.co.za', ARRAY['Ferrous Metals', 'Non-Ferrous Metals'], true),
  ('BPCR Plastics', 'Plastic recycling', '30 Nelson Road', 'Mthatha', 'Eastern Cape', '047 123 4567', 'bpcrplastics@mweb.co.za', 'www.bpcrplastics.co.za', ARRAY['Plastic'], true),
  ('Bretcor', 'Recycling solutions', '20 Mountain View', 'Bethlehem', 'Free State', '058 234 5678', 'sharon@bretcor.co.za', 'www.bretcor.co.za', ARRAY['Metal Cans', 'Paper', 'Plastic'], true),
  ('Cato Scrap', 'Metal recycling', '45 River Road', 'Vereeniging', 'Gauteng', '016 345 6789', 'grant@catoscrap.co.za', 'www.catoscrap.co.za', ARRAY['Ferrous Metals', 'Non-Ferrous Metals'], true),
  ('CCT Recycling', 'Industrial recycling', '33 Steel Road', 'Newcastle', 'KwaZulu-Natal', '034 789 1234', 'carel@cctrecycling.co.za', 'www.cctrecycling.co.za', ARRAY['Industrial Waste', 'Used Oil'], true),
  ('Cape Plastics', 'Plastic recycling', '28 Copper Road', 'Phalaborwa', 'Limpopo', '015 123 4567', 'caplastics@vodamail.co.za', 'www.capeplastics.co.za', ARRAY['Plastic'], true),
  ('Chris Dorfling', 'Recycling services', '50 Mining Street', 'Middelburg', 'Mpumalanga', '013 234 5678', 'chrisjandorfling@gmail.com', 'www.chrisdorfling.co.za', ARRAY['Ferrous Metals', 'Non-Ferrous Metals'], true),
  ('Chespak', 'Packaging recycling', '15 University Road', 'Potchefstroom', 'North West', '018 345 6789', 'peter.cook@chespak.co.za', 'www.chespak.co.za', ARRAY['E-Waste', 'Electronic Waste'], true),
  ('China Lin', 'Recycling services', '22 Copper Way', 'Springbok', 'Northern Cape', '027 123 4567', 'wangsa162lin@gmail.com', 'www.chinalin.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Carmz Recycling', 'General recycling', '40 Vine Street', 'Stellenbosch', 'Western Cape', '021 789 1234', 'carmz.raman@gmail.com', 'www.carmzrecycling.co.za', ARRAY['Glass', 'Paper', 'Metal Cans'], true),
  ('Clenchit', 'Metal recycling', '30 Beach Road', 'East London', 'Eastern Cape', '043 345 6789', 'ian@clenchit.com', 'www.clenchit.com', ARRAY['Ferrous Metals', 'Non-Ferrous Metals'], true),
  ('Collect All', 'Comprehensive recycling', '22 Main Road', 'Queenstown', 'Eastern Cape', '045 345 6789', 'jimmy@collectall.co.za', 'www.collectall.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Colour Plastic', 'Plastic recycling', '25 Frontier Road', 'Queenstown', 'Eastern Cape', '045 345 6789', 'narvesh@hotmail.com', 'www.colourplastic.co.za', ARRAY['Plastic'], true),
  ('Compact Plastic', 'Plastic recycling', '30 Berg Street', 'Harrismith', 'Free State', '058 123 4567', 'plastic@telkomsa.net', 'www.compactplastic.co.za', ARRAY['Plastic'], true),
  ('Daves Plastics', 'Plastic recycling', '55 Springs Road', 'Benoni', 'Gauteng', '011 234 5678', 'admin@davesplastics.co.za', 'www.davesplastics.co.za', ARRAY['Plastic'], true),
  ('Dawn Group', 'Industrial recycling', '20 Victoria Street', 'Ladysmith', 'KwaZulu-Natal', '036 789 1234', 'judith@dawngroup.co.za', 'www.dawngroup.co.za', ARRAY['Industrial Waste', 'Used Oil'], true),
  ('Deswalner Recycling', 'Green recycling solutions', '17 Border Road', 'Musina', 'Limpopo', '015 345 6789', 'deswalner@gmail.com', 'www.deswalnerrecycling.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Dixon Batteries', 'Battery recycling', '40 Sasol Road', 'Secunda', 'Mpumalanga', '017 123 4567', 'andre@dixonbatteries.co.za', 'www.dixonbatteries.co.za', ARRAY['Batteries'], true),
  ('Dolphin Containers', 'Container recycling', '25 Capital Way', 'Mafikeng', 'North West', '018 234 5678', 'rckl@telkomsa.net', 'www.dolphincontainers.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('DSW Waste Recycling', 'Waste management', '30 Karoo Street', 'De Aar', 'Northern Cape', '053 345 6789', 'dswwasterec@gmail.com', 'www.dswwasterecycling.co.za', ARRAY['Metal Cans', 'Paper', 'Plastic'], true),
  ('Ductile Plastics', 'Plastic manufacturing and recycling', '35 Marine Drive', 'Hermanus', 'Western Cape', '028 123 4567', 'mornay@ductileplastics.co.za', 'www.ductileplastics.co.za', ARRAY['Plastic'], true),
  ('E Olivier', 'Recycling services', '45 High Street', 'Grahamstown', 'Eastern Cape', '046 789 1234', 'eolivier.kzn@gmail.com', 'www.eolivier.co.za', ARRAY['E-Waste', 'Paper', 'Plastic'], true),
  ('ERP', 'Electronic recycling', '20 Central Road', 'Kroonstad', 'Free State', '056 345 6789', 'egw@erp.co.za', 'www.erp.co.za', ARRAY['E-Waste', 'Electronic Waste'], true),
  ('Envirobottle', 'Bottle recycling', '50 Main Reef Road', 'Krugersdorp', 'Gauteng', '011 123 4567', 'henrycbotha@gmail.com', 'www.envirobottle.co.za', ARRAY['Glass'], true),
  ('Rhino Plastics', 'Plastic recycling', '15 Industrial Road', 'Cape Town', 'Western Cape', '021 555 1234', 'brianv@rhinoplastics.co.za', 'www.rhinoplastics.co.za', ARRAY['Plastic'], true),
  ('Enping Plastic Recycling', 'Plastic recycling specialist', '42 Port Road', 'Durban', 'KwaZulu-Natal', '031 444 5678', 'enpingplasticrecycling@gmail.com', 'www.enpingrecycling.co.za', ARRAY['Plastic'], true),
  ('Envirotimbers', 'Wood recycling', '78 Main Reef Road', 'Johannesburg', 'Gauteng', '011 789 1234', 'info@envirotimbers.com', 'www.envirotimbers.com', ARRAY['Wood'], true),
  ('EWR', 'Electronic waste recycling', '25 Industrial Way', 'Port Elizabeth', 'Eastern Cape', '041 123 4567', 'ewr@vodamail.co.za', 'www.ewr.co.za', ARRAY['E-Waste', 'Electronic Waste'], true),
  ('Feli Plastics', 'Plastic recycling', '90 Church Street', 'Pretoria', 'Gauteng', '012 345 6789', 'beli@telkomsa.net', 'www.feliplastics.co.za', ARRAY['Plastic'], true),
  ('Equality Enterprise', 'Recycling solutions', '15 State Way', 'Bloemfontein', 'Free State', '051 987 6543', 'equilityenterprise@gmail.com', 'www.equalityenterprise.co.za', ARRAY['Paper', 'Plastic', 'Metal Cans'], true),
  ('Esiltuli', 'Eco-friendly recycling', '33 Riverside Road', 'Nelspruit', 'Mpumalanga', '013 555 1234', 'esiltuli@mweb.co.za', 'www.esiltuli.co.za', ARRAY['E-Waste', 'Batteries', 'Electronic Waste'], true),
  ('Excellence', 'Comprehensive recycling services', '55 Diamond Street', 'Kimberley', 'Northern Cape', '053 123 4567', 'excellence@mtnloaded.co.za', 'www.excellencerecycling.co.za', ARRAY['Industrial Waste', 'Paper', 'Plastic'], true),
  ('Extrupet', 'Plastic recycling', '12 Market Street', 'Polokwane', 'Limpopo', '015 789 1234', 'chandru@extrupet.com', 'www.extrupet.com', ARRAY['Plastic'], true),
  ('CCT Recycling', 'Comprehensive recycling facility', '15 Industrial Road', 'Cape Town', 'Western Cape', '021 555 1234', 'carel@cctrecycling.co.za', 'www.cctrecycling.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Cape Plastics', 'Plastic recycling specialist', '42 Port Road', 'Durban', 'KwaZulu-Natal', '031 444 5678', 'caplastics@vodamail.co.za', 'www.capeplastics.co.za', ARRAY['Plastic'], true),
  ('Eyethu Recycling', 'Community recycling initiative', '78 Main Reef Road', 'Johannesburg', 'Gauteng', '011 789 1234', 'eyethurec@vodamail.co.za', 'www.eyethurecycling.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Forest Recycling', 'Paper and wood recycling', '25 Industrial Way', 'Port Elizabeth', 'Eastern Cape', '041 123 4567', 'Brian.forest@wifi-mail.co.za', 'www.forestrecycling.co.za', ARRAY['Paper', 'Wood'], true),
  ('Frys Metals', 'Metal recycling specialist', '90 Church Street', 'Pretoria', 'Gauteng', '012 345 6789', 'LoganG@frys.co.za', 'www.frysmetals.co.za', ARRAY['Ferrous Metals', 'Non-Ferrous Metals'], true),
  ('Galactic Deals', 'Recycling and trading', '15 State Way', 'Bloemfontein', 'Free State', '051 987 6543', 'stu.mcmullan@gmail.com', 'www.galacticdeals.co.za', ARRAY['E-Waste', 'Metal Cans'], true),
  ('Roga Plastics', 'Plastic recycling', '33 Riverside Road', 'Nelspruit', 'Mpumalanga', '013 555 1234', 'gavin@rogaplastics.co.za', 'www.rogaplastics.co.za', ARRAY['Plastic'], true),
  ('GAP Moulding', 'Plastic recycling and manufacturing', '55 Diamond Street', 'Kimberley', 'Northern Cape', '053 123 4567', 'geoffw@gapmoulding.co.za', 'www.gapmoulding.co.za', ARRAY['Plastic'], true),
  ('Praveen Maharaj', 'Recycling services', '12 Market Street', 'Polokwane', 'Limpopo', '015 789 1234', 'praveenmaharaj15@gmail.com', 'www.praveenrecycling.co.za', ARRAY['Metal Cans', 'Industrial Waste'], true),
  ('Greenlite Concrete', 'Concrete recycling', '40 Mining Street', 'Middelburg', 'Mpumalanga', '013 234 5678', 'hilton@greenliteconcrete.co.za', 'www.greenliteconcrete.co.za', ARRAY['Industrial Waste', 'Used Oil'], true),
  ('GTC Online', 'Electronic recycling', '15 University Road', 'Potchefstroom', 'North West', '018 345 6789', 'swanepoel.w@gtconline.co.za', 'www.gtconline.co.za', ARRAY['E-Waste', 'Electronic Waste'], true),
  ('Hangerman', 'Recycling solutions', '22 Copper Way', 'Springbok', 'Northern Cape', '027 123 4567', 'neil.weston@hangerman.co.za', 'www.hangerman.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Henrial', 'General recycling', '40 Vine Street', 'Stellenbosch', 'Western Cape', '021 789 1234', 'henrial@ymail.com', 'www.henrial.co.za', ARRAY['Glass', 'Paper', 'Metal Cans'], true),
  ('Hernic Plastics', 'Plastic recycling', '30 Beach Road', 'East London', 'Eastern Cape', '043 345 6789', 'rbrasington@mweb.co.za', 'www.hernicplastics.co.za', ARRAY['Plastic'], true),
  ('Hortors', 'Paper recycling', '22 Gold Street', 'Welkom', 'Free State', '057 345 6789', 'amanda@mpmail.co.za', 'www.hortors.co.za', ARRAY['Paper'], true),
  ('Huaren Recycling', 'Comprehensive recycling', '25 Chemical Road', 'Sasolburg', 'Free State', '016 123 4567', 'sunqi891224@msn.com', 'www.huarenrecycling.co.za', ARRAY['Industrial Waste', 'Used Oil'], true),
  ('Human Metals', 'Metal recycling', '30 Railway Road', 'Springs', 'Gauteng', '011 234 5678', 'humanmetals@gmail.com', 'www.humanmetals.co.za', ARRAY['Ferrous Metals', 'Non-Ferrous Metals'], true),
  ('Habiba Alli', 'Recycling services', '35 King Shaka Road', 'Stanger', 'KwaZulu-Natal', '032 789 1234', 'habiba.alli26@gmail.com', 'www.habibarecycling.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Interwaste', 'Waste management', '40 Main Road', 'Giyani', 'Limpopo', '015 345 6789', 'derwent@netactive.co.za', 'www.interwaste.co.za', ARRAY['Metal Cans', 'Paper', 'Plastic'], true),
  ('Innovative Plastic', 'Plastic innovation and recycling', '45 Farm Road', 'Standerton', 'Mpumalanga', '017 123 4567', 'kevin@innovativeplastic.co.za', 'www.innovativeplastic.co.za', ARRAY['Plastic'], true),
  ('Iskra', 'Metal recycling', '50 Cattle Road', 'Vryburg', 'North West', '053 234 5678', 'eliran.moses@gmail.com', 'www.iskrarecycling.co.za', ARRAY['Ferrous Metals', 'Non-Ferrous Metals'], true),
  ('Harm Plastics', 'Plastic recycling', '55 Desert Road', 'Kuruman', 'Northern Cape', '053 789 1234', 'harm@telkomsa.net', 'www.harmplastics.co.za', ARRAY['Plastic'], true),
  ('Iskra', 'Metal recycling', '60 Coast Road', 'Vredenburg', 'Western Cape', '022 345 6789', 'theuns.pool@iskra.co.za', 'www.iskra.co.za', ARRAY['Metal Cans', 'Industrial Waste'], true),
  ('Isolite', 'Insulation recycling', '15 Industrial Road', 'Cape Town', 'Western Cape', '021 555 1234', 'gerrit@isolite.co.za', 'www.isolite.co.za', ARRAY['Industrial Waste'], true),
  ('Deswalner Recycling', 'Comprehensive recycling', '42 Port Road', 'Durban', 'KwaZulu-Natal', '031 444 5678', 'deswalner@gmail.com', 'www.deswalnerrecycling.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Dixon Batteries', 'Battery recycling', '78 Main Reef Road', 'Johannesburg', 'Gauteng', '011 789 1234', 'andre@dixonbatteries.co.za', 'www.dixonbatteries.co.za', ARRAY['Batteries'], true),
  ('DSW Waste Recycling', 'Waste management', '25 Industrial Way', 'Port Elizabeth', 'Eastern Cape', '041 123 4567', 'dswwasterec@gmail.com', 'www.dswrecycling.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Ductile Plastics', 'Plastic manufacturing and recycling', '90 Church Street', 'Pretoria', 'Gauteng', '012 345 6789', 'mornay@ductileplastics.co.za', 'www.ductileplastics.co.za', ARRAY['Plastic'], true),
  ('E Olivier', 'Recycling services', '15 State Way', 'Bloemfontein', 'Free State', '051 987 6543', 'eolivier.kzn@gmail.com', 'www.eolivier.co.za', ARRAY['Paper', 'Plastic', 'Metal Cans'], true),
  ('ERP', 'Electronic recycling', '33 Riverside Road', 'Nelspruit', 'Mpumalanga', '013 555 1234', 'egw@erp.co.za', 'www.erp.co.za', ARRAY['E-Waste', 'Batteries', 'Electronic Waste'], true),
  ('Envirobottle', 'Bottle recycling', '55 Diamond Street', 'Kimberley', 'Northern Cape', '053 123 4567', 'henrycbotha@gmail.com', 'www.envirobottle.co.za', ARRAY['Glass'], true),
  ('JB Plastics Recycling', 'Plastic recycling', '40 Main Road', 'Giyani', 'Limpopo', '015 345 6789', 'jbplasticsrecycling@gmail.com', 'www.jbplastics.co.za', ARRAY['Plastic'], true),
  ('JCL', 'Comprehensive recycling', '45 Farm Road', 'Standerton', 'Mpumalanga', '017 123 4567', 'john@jcl.co.za', 'www.jcl.co.za', ARRAY['Industrial Waste', 'Used Oil'], true),
  ('JDA Plastics', 'Plastic recycling', '50 Cattle Road', 'Vryburg', 'North West', '053 234 5678', 'jdaplastics@gmail.com', 'www.jdaplastics.co.za', ARRAY['Plastic'], true),
  ('Jones Recycling', 'General recycling', '55 Desert Road', 'Kuruman', 'Northern Cape', '053 789 1234', 'michaeltijones@gmail.com', 'www.jonesrecycling.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Kabel Consortium', 'Cable recycling', '60 Coast Road', 'Vredenburg', 'Western Cape', '022 345 6789', 'col@consortiumcables.com', 'www.kabelconsortium.co.za', ARRAY['Metal Cans', 'Industrial Waste'], true),
  ('Joe Magurah', 'Recycling services', '15 Industrial Road', 'Cape Town', 'Western Cape', '021 555 1234', 'joemagurah@gmail.com', 'www.joemagurah.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Koogan Plastics', 'Plastic recycling', '42 Port Road', 'Durban', 'KwaZulu-Natal', '031 444 5678', 'myi@kooganplastics.co.za', 'www.kooganplastics.co.za', ARRAY['Plastic'], true),
  ('KR Polymers', 'Polymer recycling', '78 Main Reef Road', 'Johannesburg', 'Gauteng', '011 789 1234', 'karl@krpolymers.co.za', 'www.krpolymers.co.za', ARRAY['Plastic'], true),
  ('Kru Plastics', 'Plastic recycling', '25 Industrial Way', 'Port Elizabeth', 'Eastern Cape', '041 123 4567', 'kruplastics@gmail.com', 'www.kruplastics.co.za', ARRAY['Plastic'], true),
  ('Lala Plastics', 'Plastic recycling', '90 Church Street', 'Pretoria', 'Gauteng', '012 345 6789', 'dane_platyes@yahoo.com', 'www.lalaplastics.co.za', ARRAY['Plastic'], true),
  ('Hennie Plastics', 'Plastic recycling', '15 State Way', 'Bloemfontein', 'Free State', '051 987 6543', 'hennie007@yahoo.com', 'www.hennieplastics.co.za', ARRAY['Plastic'], true),
  ('Louwrens Plastics', 'Plastic recycling', '33 Riverside Road', 'Nelspruit', 'Mpumalanga', '013 555 1234', 'alouwrens@lantic.net', 'www.louwrensplastics.co.za', ARRAY['Plastic'], true),
  ('LP Plastics', 'Plastic recycling', '55 Diamond Street', 'Kimberley', 'Northern Cape', '053 123 4567', 'lpplastic@telkomsa.net', 'www.lpplastics.co.za', ARRAY['Plastic'], true),
  ('Recycle Plastic', 'Plastic recycling', '12 Market Street', 'Polokwane', 'Limpopo', '015 789 1234', 'tony.recycleplastic@gmail.com', 'www.recycleplastic.co.za', ARRAY['Plastic'], true),
  ('LG Plastics', 'Plastic recycling', '40 Main Road', 'Giyani', 'Limpopo', '015 345 6789', 'lgplast@mweb.co.za', 'www.lgplastics.co.za', ARRAY['Plastic'], true),
  ('Gerrie Coetzer', 'Recycling services', '45 Farm Road', 'Standerton', 'Mpumalanga', '017 123 4567', 'gerriecoetzer39@gmail.com', 'www.gerriecoetzer.co.za', ARRAY['Industrial Waste', 'Used Oil'], true),
  ('Lockie Recycling', 'Comprehensive recycling', '50 Cattle Road', 'Vryburg', 'North West', '053 234 5678', 'colley.lockie1404@gmail.com', 'www.lockierecycling.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Lyk Plastics', 'Plastic recycling', '55 Desert Road', 'Kuruman', 'Northern Cape', '053 789 1234', 'lyk@mweb.co.za', 'www.lykplastics.co.za', ARRAY['Plastic'], true),
  ('Tuffloors', 'Flooring recycling', '60 Coast Road', 'Vredenburg', 'Western Cape', '022 345 6789', 'info@tuffloors.co.za', 'www.tuffloors.co.za', ARRAY['Industrial Waste'], true),
  ('Malta Recycling', 'Metal recycling', '15 Industrial Road', 'Cape Town', 'Western Cape', '021 555 1234', 'newby.sa@gmail.com', 'www.maltarecycling.com', ARRAY['Ferrous Metals', 'Non-Ferrous Metals'], true),
  ('McGinns', 'Industrial recycling', '42 Port Road', 'Durban', 'KwaZulu-Natal', '031 444 5678', 'ianv@mcgind.co.za', 'www.mcginns.co.za', ARRAY['Industrial Waste', 'Used Oil'], true),
  ('Nampak', 'Packaging recycling', '78 Main Reef Road', 'Johannesburg', 'Gauteng', '011 789 1234', 'info@nampak.com', 'www.nampak.com', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('MFI Mouldings', 'Plastic recycling', '25 Industrial Way', 'Port Elizabeth', 'Eastern Cape', '041 123 4567', 'mfix@mfinaci.co.za', 'www.mfimouldings.co.za', ARRAY['Plastic'], true),
  ('Office Furniture Africa', 'Furniture recycling', '90 Church Street', 'Pretoria', 'Gauteng', '012 345 6789', 'gill@officefurnitureafrica.com', 'www.officefurnitureafrica.co.za', ARRAY['Wood', 'Metal'], true),
  ('Motech', 'Electronic recycling', '15 State Way', 'Bloemfontein', 'Free State', '051 987 6543', 'motech3@gmail.com', 'www.motech.co.za', ARRAY['E-Waste', 'Electronic Waste'], true),
  ('MPC', 'Plastic recycling', '33 Riverside Road', 'Nelspruit', 'Mpumalanga', '013 555 1234', 'royp@mpcsa.co.za', 'www.mpc.co.za', ARRAY['Plastic'], true),
  ('Mpact', 'Paper recycling', '55 Diamond Street', 'Kimberley', 'Northern Cape', '053 123 4567', 'rfairbanks@mpact.co.za', 'www.mpact.co.za', ARRAY['Paper'], true),
  ('Rothman Plastics', 'Plastic recycling', '12 Market Street', 'Polokwane', 'Limpopo', '015 789 1234', 'rothman@netactive.co.za', 'www.rothmanplastics.co.za', ARRAY['Plastic'], true),
  ('Andre Plastic', 'Plastic recycling', '40 Main Road', 'Giyani', 'Limpopo', '015 345 6789', 'andre.plastic@gmail.com', 'www.andreplastic.co.za', ARRAY['Plastic'], true),
  ('MX Recyclers', 'Metal recycling', '45 Farm Road', 'Standerton', 'Mpumalanga', '017 123 4567', 'mxrecyclers@gmail.com', 'www.mxrecyclers.co.za', ARRAY['Ferrous Metals', 'Non-Ferrous Metals'], true),
  ('MyPlas', 'Plastic recycling', '50 Cattle Road', 'Vryburg', 'North West', '053 234 5678', 'walter@myplas.co.za', 'www.myplas.co.za', ARRAY['Plastic'], true),
  ('Nardo Plastics', 'Plastic recycling', '55 Desert Road', 'Kuruman', 'Northern Cape', '053 789 1234', 'nardo@africhair.co.za', 'www.africhair.co.za', ARRAY['Plastic'], true),
  ('Rugged Products', 'Recycled products manufacturing', '60 Coast Road', 'Vredenburg', 'Western Cape', '022 345 6789', 'ruggedproducts@yahoo.com', 'ruggedproducts.co.za', ARRAY['Plastic', 'Metal'], true),
  ('Think Twice', 'Recycling solutions', '15 Industrial Road', 'Cape Town', 'Western Cape', '021 555 1234', 'john@thinktwice.co.za', 'www.thinktwice.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('New World', 'Recycling services', '42 Port Road', 'Durban', 'KwaZulu-Natal', '031 444 5678', 'leo@newwo.co.za', 'www.newworld.co.za', ARRAY['Metal Cans', 'Industrial Waste'], true),
  ('NWD Plastics', 'Plastic recycling', '78 Main Reef Road', 'Johannesburg', 'Gauteng', '011 789 1234', 'mark@nwdplastics.co.za', 'www.nwdplastics.co.za', ARRAY['Plastic'], true),
  ('Outeniqua Plastics', 'Plastic recycling', '25 Industrial Way', 'Port Elizabeth', 'Eastern Cape', '041 123 4567', 'manager@outeniquaplastics.co.za', 'www.outeniquaplastics.co.za', ARRAY['Plastic'], true),
  ('Pak Plastics', 'Plastic packaging recycling', '90 Church Street', 'Pretoria', 'Gauteng', '012 345 6789', 'ridwaan@pakplastics.co.za', 'www.pakplastics.co.za', ARRAY['Plastic'], true),
  ('Pelmanco', 'Industrial recycling', '15 State Way', 'Bloemfontein', 'Free State', '051 987 6543', 'recycling@pelmanco.co.za', 'www.pelmanco.co.za', ARRAY['Industrial Waste', 'Used Oil'], true),
  ('Trekliners', 'Recycling solutions', '33 Riverside Road', 'Nelspruit', 'Mpumalanga', '013 555 1234', 'davidtruter@trekliners.co.za', 'www.trekliners.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Oilcor', 'Oil recycling', '55 Diamond Street', 'Kimberley', 'Northern Cape', '053 123 4567', 'oilcoradmin@telkomsa.net', 'www.oilcor.co.za', ARRAY['Used Oil'], true),
  ('Plastex', 'Plastic recycling', '12 Market Street', 'Polokwane', 'Limpopo', '015 789 1234', 'plastex@telkomsa.net', 'www.plastex.co.za', ARRAY['Plastic'], true),
  ('PP Extruders', 'Plastic extrusion and recycling', '40 Main Road', 'Giyani', 'Limpopo', '015 345 6789', 'ppextruders@gmail.com', 'www.ppextruders.co.za', ARRAY['Plastic'], true),
  ('MEPS Pipes', 'Pipe recycling', '45 Farm Road', 'Standerton', 'Mpumalanga', '017 123 4567', 'meps@mepsef.com', 'www.mepspipes.co.za', ARRAY['Plastic'], true),
  ('Plastdebra', 'Plastic recycling', '50 Cattle Road', 'Vryburg', 'North West', '053 234 5678', 'Bernard@plastdebra.co.za', 'www.plastdebra.co.za', ARRAY['Plastic'], true),
  ('Plastic Revolutions', 'Innovative plastic recycling', '55 Desert Road', 'Kuruman', 'Northern Cape', '053 789 1234', 'duane@plasticrevolutions.co.za', 'www.plasticrevolutions.co.za', ARRAY['Plastic'], true),
  ('Plasticomp', 'Plastic composite recycling', '60 Coast Road', 'Vredenburg', 'Western Cape', '022 345 6789', 'atjabring@plasticomp.co.za', 'www.plasticomp.co.za', ARRAY['Plastic'], true),
  ('Fosters Operations', 'Industrial recycling', '15 Industrial Road', 'Cape Town', 'Western Cape', '021 555 1234', 'fostersops@absamail.co.za', 'www.fostersoperations.co.za', ARRAY['Industrial Waste', 'Used Oil'], true),
  ('Polyash', 'Plastic recycling', '42 Port Road', 'Durban', 'KwaZulu-Natal', '031 444 5678', 'polyash@global.co.za', 'www.polyash.co.za', ARRAY['Plastic'], true),
  ('Polyga Plastics', 'Plastic recycling', '78 Main Reef Road', 'Johannesburg', 'Gauteng', '011 789 1234', 'polygaplastics@yahoo.com.tw', 'www.polygaplastics.co.za', ARRAY['Plastic'], true),
  ('Polymark', 'Plastic marking and recycling', '25 Industrial Way', 'Port Elizabeth', 'Eastern Cape', '041 123 4567', 'rudi@polymark.co.za', 'www.polymark.co.za', ARRAY['Plastic'], true),
  ('Polyplank', 'Plastic plank manufacturing and recycling', '90 Church Street', 'Pretoria', 'Gauteng', '012 345 6789', 'jakes@polyplank.co.za', 'www.polyplank.co.za', ARRAY['Plastic'], true),
  ('Potch Plastic', 'Plastic recycling', '15 State Way', 'Bloemfontein', 'Free State', '051 987 6543', 'dvbreda@potchplastic.co.za', 'www.potchplastic.co.za', ARRAY['Plastic'], true),
  ('Porra Plastics', 'Plastic recycling', '33 Riverside Road', 'Nelspruit', 'Mpumalanga', '013 555 1234', 'porra@yebo.co.za', 'www.porraplastics.co.za', ARRAY['Plastic'], true),
  ('Reclaim Plastics', 'Plastic reclamation', '55 Diamond Street', 'Kimberley', 'Northern Cape', '053 123 4567', 'j.degenaar@yahoo.com', 'www.reclaimplastics.co.za', ARRAY['Plastic'], true),
  ('RJR Plastics', 'Plastic recycling', '12 Market Street', 'Polokwane', 'Limpopo', '015 789 1234', 'rjr@telkomsa.net', 'www.rjrplastics.co.za', ARRAY['Plastic'], true),
  ('Reclaim', 'General recycling', '40 Main Road', 'Giyani', 'Limpopo', '015 345 6789', 'reclaim@telkomsa.net', 'www.reclaim.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Sydney Human', 'Recycling services', '45 Farm Road', 'Standerton', 'Mpumalanga', '017 123 4567', 'sydneyhuman@vodamail.co.za', 'www.sydneyhuman.co.za', ARRAY['Industrial Waste', 'Used Oil'], true),
  ('Reclam', 'Comprehensive recycling', '50 Cattle Road', 'Vryburg', 'North West', '053 234 5678', 'lood1963@gmail.com', 'www.reclam.co.za', ARRAY['Ferrous Metals', 'Non-Ferrous Metals'], true),
  ('Recyclit', 'Recycling solutions', '55 Desert Road', 'Kuruman', 'Northern Cape', '053 789 1234', 'garth@recyclit.co.za', 'www.recyclit.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Reproplast', 'Plastic recycling', '60 Coast Road', 'Vredenburg', 'Western Cape', '022 345 6789', 'zirk@reproplast.co.za', 'www.reproplast.co.za', ARRAY['Plastic'], true),
  ('Rhino Plastics', 'Plastic recycling', '15 Industrial Road', 'Cape Town', 'Western Cape', '021 555 1234', 'rob@rhinoplastics.co.za', 'www.rhinoplastics.co.za', ARRAY['Plastic'], true),
  ('Rims Plastic', 'Plastic recycling', '42 Port Road', 'Durban', 'KwaZulu-Natal', '031 444 5678', 'vayani@rimsplastic.co.za', 'www.rimsplastic.co.za', ARRAY['Plastic'], true),
  ('Robus Industrial', 'Industrial recycling', '78 Main Reef Road', 'Johannesburg', 'Gauteng', '011 789 1234', 'robusindustrial@worldonline.co.za', 'www.robusindustrial.co.za', ARRAY['Industrial Waste', 'Used Oil'], true),
  ('SA Converting', 'Paper conversion and recycling', '25 Industrial Way', 'Port Elizabeth', 'Eastern Cape', '041 123 4567', 'rajiv@saconverting.co.za', 'www.saconverting.co.za', ARRAY['Paper'], true),
  ('SAPM', 'Plastic manufacturing and recycling', '90 Church Street', 'Pretoria', 'Gauteng', '012 345 6789', 'sapm@satweb.co.za', 'www.sapm.co.za', ARRAY['Plastic'], true),
  ('Safa Plastics', 'Plastic recycling', '15 State Way', 'Bloemfontein', 'Free State', '051 987 6543', 'safaplastics@yahoo.com', 'www.safaplastics.co.za', ARRAY['Plastic'], true),
  ('Sams Plastics', 'Plastic recycling', '33 Riverside Road', 'Nelspruit', 'Mpumalanga', '013 555 1234', 'samsplastics@mweb.co.za', 'www.samsplastics.co.za', ARRAY['Plastic'], true),
  ('Scrapex', 'Metal recycling', '55 Diamond Street', 'Kimberley', 'Northern Cape', '053 123 4567', 'jacques@scrapex.co.za', 'www.scrapex.co.za', ARRAY['Ferrous Metals', 'Non-Ferrous Metals'], true),
  ('SLD', 'Recycling services', '12 Market Street', 'Polokwane', 'Limpopo', '015 789 1234', 'sldfrb@hotmail.com', 'www.sld.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Shanbhu Investments', 'Recycling investments', '40 Main Road', 'Giyani', 'Limpopo', '015 345 6789', 'shanbhuinvestments@gmail.com', 'www.shanbhuinvestments.co.za', ARRAY['Metal Cans', 'Paper', 'Plastic'], true),
  ('Schoeman Recycling', 'Comprehensive recycling', '45 Farm Road', 'Standerton', 'Mpumalanga', '017 123 4567', 'jo.schoeman@gmail.com', 'www.schoemanrecycling.co.za', ARRAY['Industrial Waste', 'Used Oil'], true),
  ('Shirleys Recycling', 'Community recycling', '50 Cattle Road', 'Vryburg', 'North West', '053 234 5678', 'shirleys-recycling@live.co.za', 'www.shirleysrecycling.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Sindawonye', 'Recycling solutions', '55 Desert Road', 'Kuruman', 'Northern Cape', '053 789 1234', 'tervet@mweb.co.za', 'www.sindawonye.co.za', ARRAY['Metal Cans', 'Paper', 'Plastic'], true),
  ('SKG Plastics', 'Plastic recycling', '60 Coast Road', 'Vredenburg', 'Western Cape', '022 345 6789', 'skgplastics@gmail.com', 'www.skgplastics.co.za', ARRAY['Plastic'], true),
  ('Smart Matta', 'Innovative recycling solutions', '15 Industrial Road', 'Cape Town', 'Western Cape', '021 555 1234', 'sunilr@smartmatta.com', 'smartmatta.co.za', ARRAY['E-Waste', 'Electronic Waste'], true),
  ('Some Plastic', 'Plastic recycling', '42 Port Road', 'Durban', 'KwaZulu-Natal', '031 444 5678', 'admin@someplastic.co.za', 'www.someplastic.co.za', ARRAY['Plastic'], true),
  ('Lava Plastic', 'Plastic recycling', '78 Main Reef Road', 'Johannesburg', 'Gauteng', '011 789 1234', 'krw@telkomsa.net', 'www.lavaplastic.co.za', ARRAY['Plastic'], true),
  ('Sims Recycling', 'Metal recycling', '25 Industrial Way', 'Port Elizabeth', 'Eastern Cape', '041 123 4567', 'jimins@yahoo.com', 'www.simsrecycling.co.za', ARRAY['Ferrous Metals', 'Non-Ferrous Metals'], true),
  ('Stuart', 'Industrial recycling', '90 Church Street', 'Pretoria', 'Gauteng', '012 345 6789', 'mds@stuart.co.za', 'www.stuart.co.za', ARRAY['Industrial Waste', 'Used Oil'], true),
  ('Wade Pipe', 'Pipe recycling', '15 State Way', 'Bloemfontein', 'Free State', '051 987 6543', 'hassen@wadepipe.co.za', 'www.wadepipe.co.za', ARRAY['Plastic'], true),
  ('Supaplas', 'Plastic recycling', '33 Riverside Road', 'Nelspruit', 'Mpumalanga', '013 555 1234', 'supaplas@mweb.co.za', 'www.supaplas.co.za', ARRAY['Plastic'], true),
  ('FSV', 'Recycling services', '55 Diamond Street', 'Kimberley', 'Northern Cape', '053 123 4567', 'francois@fsv.co.za', 'www.fsv.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Artistic Moulding', 'Plastic moulding and recycling', '12 Market Street', 'Polokwane', 'Limpopo', '015 789 1234', 'andrew@artisticmoulding.co.za', 'www.artisticmoulding.co.za', ARRAY['Plastic'], true),
  ('Van Rensburg', 'Recycling services', '40 Main Road', 'Giyani', 'Limpopo', '015 345 6789', 'vanrensburghd@gmail.com', 'www.vanrensburg.co.za', ARRAY['Metal Cans', 'Paper', 'Plastic'], true),
  ('TAS Plastics', 'Plastic recycling', '45 Farm Road', 'Standerton', 'Mpumalanga', '017 123 4567', 'transafrica@telkomsa.net', 'www.tasplastics.co.za', ARRAY['Plastic'], true),
  ('Thenga Plastics', 'Plastic recycling', '50 Cattle Road', 'Vryburg', 'North West', '053 234 5678', 'bronwyn@thengaplastics.co.za', 'www.thengaplastics.co.za', ARRAY['Plastic'], true),
  ('Timber Solutions PE', 'Wood recycling', '55 Desert Road', 'Kuruman', 'Northern Cape', '053 789 1234', 'timbersolutionspe@telkomsa.net', 'www.timbersolutionspe.co.za', ARRAY['Wood'], true),
  ('Tomasek', 'Recycling services', '60 Coast Road', 'Vredenburg', 'Western Cape', '022 345 6789', 'tomaszektx@yahoo.com', 'www.tomasek.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true),
  ('Transpaco', 'Packaging recycling', '15 Industrial Road', 'Cape Town', 'Western Cape', '021 555 1234', 'jaco.breytenbach@transpaco.co.za', 'www.transpaco.co.za', ARRAY['Paper', 'Plastic'], true),
  ('Woejan', 'Recycling services', '42 Port Road', 'Durban', 'KwaZulu-Natal', '031 444 5678', 'woejan@yahoo.com', 'www.woejan.co.za', ARRAY['Metal Cans', 'Industrial Waste'], true),
  ('Universal Recycling', 'Comprehensive recycling', '78 Main Reef Road', 'Johannesburg', 'Gauteng', '011 789 1234', 'christod.potgieter@gmail.com', 'www.universalrecycling.co.za', ARRAY['Paper', 'Plastic', 'Glass'], true);

-- Add service offerings, container types, and other details to the newly added recyclers
UPDATE recyclers
SET 
  service_offerings = ARRAY['Collection', 'Drop-off', 'Container Rental'],
  container_types = ARRAY['Bags (100L)', '240L Bins', '6m³ Skips', '12m³ Skips'],
  minimum_weight = 100.0,
  payment_terms = 'Payment on collection/delivery',
  operating_hours = 'Mon-Fri: 08:00-17:00, Sat: 08:00-13:00'
WHERE name IN ('Unica', 'Abacus', 'Abbys Machines', 'Africhair', 'Afripipe', 'Alex Plastics');

-- Update some recyclers with different service offerings and container types
UPDATE recyclers
SET 
  service_offerings = ARRAY['Drop-off', 'Industrial Services'],
  container_types = ARRAY['Bags (100L)', '240L Bins'],
  minimum_weight = 50.0,
  payment_terms = 'EFT within 24 hours',
  operating_hours = 'Mon-Fri: 07:30-16:30'
WHERE name IN ('Allsure Traders', 'Alrette', 'Alurite Services', 'AM Recycling', 'Anchor Recycling');

-- Update some recyclers with different minimum weights
UPDATE recyclers
SET 
  minimum_weight = 200.0
WHERE name IN ('AA Recycling Group', 'Antiwaste', 'APR Recycling', 'APR1', 'B4 Plastics');

-- Update verification status for some recyclers
UPDATE recyclers
SET 
  verified = false
WHERE name IN ('Bantjes Recycling', 'BB Plastics', 'Belltone Trading', 'BPCR Plastics', 'Bretcor');