-- Clear existing data
TRUNCATE TABLE recyclers;

-- Insert real recycling companies from search results
INSERT INTO recyclers (
  name, description, address, city, province, 
  phone, email, website, materials, verified,
  latitude, longitude, service_offerings, container_types,
  minimum_weight, operating_hours
) VALUES 
  (
    'Reclam',
    'Leading recycling and packaging company in South Africa',
    '316 Derdepoort Road, Silverton',
    'Pretoria',
    'Gauteng',
    '012 842 5000',
    'info@reclam.co.za',
    'www.reclam.co.za',
    ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
    true,
    -25.735365,
    28.275198,
    ARRAY['Collection', 'Drop-off'],
    ARRAY['Bags', '240L Bins'],
    100.0,
    'Mon-Fri: 08:00-16:30'
  ),
  (
    'Waste Plan',
    'Integrated waste management solutions',
    '16 Dawn Road, Montague Gardens',
    'Cape Town',
    'Western Cape',
    '021 512 4000',
    'info@wasteplan.co.za',
    'www.wasteplan.co.za',
    ARRAY['General Waste', 'Recyclables', 'Industrial Waste'],
    true,
    -33.931139,
    18.539041,
    ARRAY['Collection', 'Waste Management'],
    ARRAY['Bins', 'Skips'],
    50.0,
    'Mon-Fri: 07:00-17:00'
  ),
  (
    'Oricol Environmental Services',
    'Environmental and waste management specialists',
    '22 Angus Crescent, Longmeadow',
    'Johannesburg',
    'Gauteng',
    '011 323 7300',
    'info@oricol.co.za',
    'www.oricol.co.za',
    ARRAY['Industrial Waste', 'Hazardous Waste', 'Recyclables'],
    true,
    -26.208790,
    28.984789,
    ARRAY['Collection', 'Waste Management', 'Consulting'],
    ARRAY['Specialized Containers'],
    200.0,
    'Mon-Fri: 08:00-17:00'
  ),
  (
    'Interwaste',
    'Integrated waste management solutions',
    '2 Brammer Road, Industries East',
    'Germiston',
    'Gauteng',
    '011 323 7300',
    'info@interwaste.co.za',
    'www.interwaste.co.za',
    ARRAY['Industrial Waste', 'General Waste', 'Recyclables'],
    true,
    -26.208790,
    28.984789,
    ARRAY['Collection', 'Waste Management'],
    ARRAY['Bins', 'Skips'],
    100.0,
    'Mon-Fri: 07:00-16:00'
  ),
  (
    'Waste Group',
    'Comprehensive waste management services',
    '14 Pomona Road, Pomona',
    'Kempton Park',
    'Gauteng',
    '011 979 1885',
    'info@wastegroup.co.za',
    'www.wastegroup.co.za',
    ARRAY['General Waste', 'Recyclables', 'Industrial Waste'],
    true,
    -26.208790,
    28.984789,
    ARRAY['Collection', 'Recycling'],
    ARRAY['Bins', 'Skips'],
    50.0,
    'Mon-Fri: 08:00-16:30'
  ),
  (
    'Don''t Waste',
    'Integrated waste management solutions',
    '38 Wrench Road, Isando',
    'Johannesburg',
    'Gauteng',
    '011 878 0000',
    'info@dontwaste.co.za',
    'www.dontwaste.co.za',
    ARRAY['General Waste', 'Recyclables'],
    true,
    -26.208790,
    28.984789,
    ARRAY['Collection', 'Waste Management'],
    ARRAY['Bins', 'Skips'],
    100.0,
    'Mon-Fri: 07:00-16:00'
  ),
  (
    'Averda South Africa',
    'International waste management company',
    '19 Piet Rautenbach Street, Elsies River',
    'Cape Town',
    'Western Cape',
    '021 534 3345',
    'info.sa@averda.com',
    'www.averda.co.za',
    ARRAY['Industrial Waste', 'Hazardous Waste', 'Recyclables'],
    true,
    -33.931139,
    18.539041,
    ARRAY['Collection', 'Treatment'],
    ARRAY['Specialized Containers'],
    200.0,
    'Mon-Fri: 08:00-17:00'
  ),
  (
    'EnviroServ',
    'Waste management provider',
    '27 Bessemer Street, Heriotdale',
    'Johannesburg',
    'Gauteng',
    '011 456 5400',
    'info@enviroserv.co.za',
    'www.enviroserv.co.za',
    ARRAY['Hazardous Waste', 'Industrial Waste', 'General Waste'],
    true,
    -26.208790,
    28.984789,
    ARRAY['Collection', 'Treatment'],
    ARRAY['Specialized Containers'],
    200.0,
    'Mon-Fri: 07:30-16:30'
  ),
  (
    'Desco Electronic Recyclers',
    'E-waste recycling specialists',
    '5 Plantation Road, Eastgate Ext 18',
    'Sandton',
    'Gauteng',
    '011 894 7730',
    'info@desco.co.za',
    'www.desco.co.za',
    ARRAY['E-Waste', 'Electronic Components'],
    true,
    -26.208790,
    28.984789,
    ARRAY['Collection', 'Data Destruction'],
    ARRAY['Secure Containers'],
    50.0,
    'Mon-Fri: 08:00-16:30'
  ),
  (
    'Green Office',
    'Printer cartridge recycling specialists',
    '13 Moorsom Avenue, Epping 1',
    'Cape Town',
    'Western Cape',
    '021 532 1780',
    'info@greenoffice.co.za',
    'www.greenoffice.co.za',
    ARRAY['Printer Cartridges', 'E-Waste'],
    true,
    -33.931139,
    18.539041,
    ARRAY['Collection', 'Recycling'],
    ARRAY['Secure Boxes'],
    25.0,
    'Mon-Fri: 08:30-17:00'
  );

-- Add indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_recyclers_province ON recyclers(province);
CREATE INDEX IF NOT EXISTS idx_recyclers_city ON recyclers(city);
CREATE INDEX IF NOT EXISTS idx_recyclers_materials ON recyclers USING GIN(materials);
CREATE INDEX IF NOT EXISTS idx_recyclers_verified ON recyclers(verified);