-- Clear existing data
TRUNCATE TABLE recyclers;

-- Insert real recycling companies from South Africa
INSERT INTO recyclers (
  name, description, address, city, province, 
  phone, email, website, materials, verified,
  latitude, longitude, service_offerings, container_types,
  minimum_weight, operating_hours
) VALUES 
  -- From search results
  (
    'Reclam',
    'Leading recycling company in South Africa',
    '41 Barlow Street, Germiston',
    'Johannesburg',
    'Gauteng',
    '011 824 7804',
    'info@reclam.co.za',
    'www.reclam.co.za',
    ARRAY['Paper', 'Plastic', 'Metal', 'Glass'],
    true,
    -26.208790,
    28.984789,
    ARRAY['Collection', 'Drop-off', 'Container Rental'],
    ARRAY['Bags', '240L Bins', '6m³ Skips'],
    100.0,
    'Mon-Fri: 08:00-16:30'
  ),
  (
    'Waste Plan',
    'Integrated waste management solutions',
    '16 Dawn Road, Montague Gardens',
    'Cape Town',
    'Western Cape',
    '021 512 4000',
    'info@wasteplan.co.za',
    'www.wasteplan.co.za',
    ARRAY['General Waste', 'Recyclables', 'Hazardous Waste'],
    true,
    -33.931139,
    18.539041,
    ARRAY['Collection', 'Waste Management', 'Consulting'],
    ARRAY['Bags', '240L Bins', '6m³ Skips'],
    50.0,
    'Mon-Fri: 07:00-17:00'
  ),
  (
    'Oricol Environmental Services',
    'Environmental and waste management specialists',
    '28 Forge Road, Spartan',
    'Johannesburg',
    'Gauteng',
    '011 323 7300',
    'info@oricol.co.za',
    'www.oricol.co.za',
    ARRAY['Industrial Waste', 'Hazardous Waste', 'Recyclables'],
    true,
    -26.208790,
    28.984789,
    ARRAY['Collection', 'Waste Management', 'Consulting'],
    ARRAY['Bins', 'Skips', 'Specialized Containers'],
    100.0,
    'Mon-Fri: 08:00-17:00'
  ),
  (
    'Interwaste',
    'Integrated waste management and recycling solutions',
    '2 Brammer Road, Industries West',
    'Germiston',
    'Gauteng',
    '011 323 7300',
    'info@interwaste.co.za',
    'www.interwaste.co.za',
    ARRAY['Industrial Waste', 'General Waste', 'Recyclables', 'Hazardous Waste'],
    true,
    -26.208790,
    28.984789,
    ARRAY['Collection', 'Waste Management', 'Recycling'],
    ARRAY['Bins', 'Skips', 'Specialized Containers'],
    100.0,
    'Mon-Fri: 07:00-17:00'
  ),
  (
    'Waste Group',
    'Comprehensive waste management services',
    '12 Axle Drive, Clayville',
    'Midrand',
    'Gauteng',
    '010 595 4355',
    'info@wastegroup.co.za',
    'www.wastegroup.co.za',
    ARRAY['General Waste', 'Recyclables', 'Industrial Waste'],
    true,
    -26.208790,
    28.984789,
    ARRAY['Collection', 'Recycling', 'Waste Management'],
    ARRAY['Bins', 'Skips'],
    50.0,
    'Mon-Fri: 08:00-16:30'
  ),
  (
    'Don''t Waste',
    'Integrated waste management solutions',
    '23 Galaxy Avenue, Linbro Business Park',
    'Sandton',
    'Gauteng',
    '087 803 3624',
    'info@dontwaste.co.za',
    'www.dontwaste.co.za',
    ARRAY['General Waste', 'Recyclables', 'Organic Waste'],
    true,
    -26.208790,
    28.984789,
    ARRAY['Collection', 'Recycling', 'Waste Management'],
    ARRAY['Bins', 'Skips', 'Compactors'],
    100.0,
    'Mon-Fri: 07:00-17:00'
  ),
  (
    'Averda South Africa',
    'International waste management company',
    '42 Electron Avenue, Isando',
    'Johannesburg',
    'Gauteng',
    '011 977 1754',
    'info.rsa@averda.com',
    'www.averda.co.za',
    ARRAY['Hazardous Waste', 'Medical Waste', 'Industrial Waste', 'Recyclables'],
    true,
    -26.208790,
    28.984789,
    ARRAY['Collection', 'Treatment', 'Disposal'],
    ARRAY['Specialized Containers', 'Bins', 'Skips'],
    100.0,
    'Mon-Fri: 08:00-17:00'
  ),
  (
    'EnviroServ',
    'Waste management solutions provider',
    '2 Brammer Road, Industries West',
    'Germiston',
    'Gauteng',
    '011 456 5400',
    'info@enviroserv.co.za',
    'www.enviroserv.co.za',
    ARRAY['Hazardous Waste', 'Industrial Waste', 'General Waste'],
    true,
    -26.208790,
    28.984789,
    ARRAY['Collection', 'Treatment', 'Disposal'],
    ARRAY['Specialized Containers', 'Bins', 'Skips'],
    100.0,
    'Mon-Fri: 07:00-16:30'
  ),
  (
    'Desco Electronic Recyclers',
    'E-waste recycling specialists',
    '16 Basalt Street, Alrode',
    'Johannesburg',
    'Gauteng',
    '011 864 3723',
    'info@desco.co.za',
    'www.desco.co.za',
    ARRAY['E-Waste', 'Electronic Waste', 'Computers', 'Appliances'],
    true,
    -26.208790,
    28.984789,
    ARRAY['Collection', 'Recycling', 'Data Destruction'],
    ARRAY['Specialized Containers'],
    50.0,
    'Mon-Fri: 08:00-16:30'
  ),
  (
    'Green Office',
    'Printer cartridge and e-waste recycling',
    '37 Gillitts Road, Pinetown',
    'Durban',
    'KwaZulu-Natal',
    '031 705 3595',
    'info@greenoffice.co.za',
    'www.greenoffice.co.za',
    ARRAY['Printer Cartridges', 'E-Waste', 'Office Equipment'],
    true,
    -29.921900,
    31.001926,
    ARRAY['Collection', 'Recycling'],
    ARRAY['Specialized Containers'],
    25.0,
    'Mon-Fri: 08:00-16:30'
  );

-- Add indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_recyclers_province ON recyclers(province);
CREATE INDEX IF NOT EXISTS idx_recyclers_city ON recyclers(city);
CREATE INDEX IF NOT EXISTS idx_recyclers_materials ON recyclers USING GIN(materials);
CREATE INDEX IF NOT EXISTS idx_recyclers_verified ON recyclers(verified);